name: Simple CI Lab

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.12", "3.14" ]
        

    env:
      APP_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run app
        run: |
          python app.py

      - name: Echo GitHub env vars
        run: |
          echo "Branch: $GITHUB_REF"
          echo "Commit: $GITHUB_SHA"
          echo "Runner OS: $RUNNER_OS"

      - name: Generate report
        run: |
          echo "Test ran on ${{ matrix.python-version }}" > report.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.python-version }}
          path: report.txt

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app"